"""Fact extraction add-on for chunks.

Extracts factual statements from chunks using LLM analysis.
Stores extracted facts in chunk.metadata.extra["facts"] as a list of strings.
"""

import json
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from spiderweb.config import settings
from spiderweb.observability.logging_config import get_logger
from spiderweb.utils.llm_structured import model_from_structured_complete
from superglue import structured_complete

if TYPE_CHECKING:
    from spiderweb.models.document import Chunk, Document

logger = get_logger(__name__)


class FactsResponse(BaseModel):
    """LLM output for fact extraction.
    
    Generated by analyzing chunk content and extracting factual statements.
    """

    facts: list[str] = Field(
        description="List of factual statements extracted from the chunk",
        default_factory=list,
    )


class FactsAddOn:
    """Add-on that extracts facts from chunks.
    
    For each chunk, uses an LLM to identify and extract factual statements.
    Stores the facts in chunk.metadata.extra["facts"] as a list of strings.
    
    Example:
        >>> from superglue import GlueLLM
        >>> from spiderweb.addons.facts import FactsAddOn
        >>> 
        >>> llm = GlueLLM()
        >>> addon = FactsAddOn(llm_client=llm)
        >>> chunks = await addon.process_async(chunks)
        >>> # Facts are now in chunk.metadata.extra["facts"]
    """

    def __init__(
        self,
        llm_client: Any | None = None,
        model: str | None = None,
        max_facts: int = 10,
    ) -> None:
        """Initialize facts add-on.
        
        Args:
            llm_client: GlueLLM client for LLM operations (required)
            model: Optional model name override
            max_facts: Maximum number of facts to extract per chunk
        """
        self.llm_client = llm_client
        self.model = model
        self.max_facts = max_facts

    async def process_async(
        self,
        chunks: "list[Chunk]",
        *,
        document: "Document | None" = None,
        **kwargs: object,
    ) -> "list[Chunk]":
        """Extract facts from chunks asynchronously.
        
        Args:
            chunks: List of chunks to process
            document: Optional parent document (for context)
            **kwargs: Additional context from the pipeline
            
        Returns:
            The same list of chunks (after mutation)
        """
        if not self.llm_client:
            logger.warning("FactsAddOn: No LLM client provided, skipping fact extraction")
            return chunks

        for chunk in chunks:
            try:
                facts = await self._extract_facts(chunk.content)
                chunk.metadata.extra["facts"] = facts
                logger.debug(f"Extracted {len(facts)} facts from chunk {chunk.id[:8]}")
            except Exception as e:
                logger.warning(f"Failed to extract facts from chunk {chunk.id[:8]}: {e}")
                chunk.metadata.extra["facts"] = []

        return chunks

    def process(
        self,
        chunks: "list[Chunk]",
        *,
        document: "Document | None" = None,
        **kwargs: object,
    ) -> "list[Chunk]":
        """Process chunks synchronously (not supported, raises error).
        
        Facts extraction requires async LLM calls, so this method is not supported.
        Use process_async() instead.
        """
        raise NotImplementedError("FactsAddOn requires async processing. Use process_async() instead.")

    async def _extract_facts(self, content: str) -> list[str]:
        """Extract facts from chunk content using LLM.
        
        Args:
            content: The chunk content to analyze
            
        Returns:
            List of factual statements extracted from the content
        """
        prompt = f"""Extract factual statements from the following text.

Focus on:
- Concrete, verifiable facts (dates, numbers, names, locations, events)
- Objective statements that can be verified
- Avoid opinions, speculation, or meta-commentary about the text itself

Text to analyze:
{content}

Return a JSON object with a "facts" array containing the extracted facts.
Each fact should be a concise, standalone statement.
Limit to {self.max_facts} facts maximum."""

        try:
            # Try structured_complete first (preferred)
            try:
                raw = await structured_complete(
                    user_message=prompt,
                    response_format=FactsResponse,
                    model=self.model,
                    timeout=settings.llm_timeout,
                )
                parsed = model_from_structured_complete(raw, FactsResponse)
                facts = parsed.facts[:self.max_facts] if parsed.facts else []
                return facts
            except (ImportError, AttributeError, Exception) as e:
                logger.debug(f"structured_complete not available, falling back to complete(): {e}")
                # Fallback to complete() + JSON parse
                pass
        except Exception:
            # Fallback to complete() + JSON parse
            pass

        # Fallback: use complete() and parse JSON
        complete_kwargs: dict[str, Any] = {
            "user_message": prompt,
            "temperature": 0.3,  # Lower temperature for more consistent extraction
            "timeout": settings.llm_timeout,
        }
        if self.model is not None:
            complete_kwargs["model"] = self.model

        try:
            response = await self.llm_client.complete(**complete_kwargs)
        except TypeError:
            # Handle clients that don't accept these kwargs
            complete_kwargs.pop("temperature", None)
            complete_kwargs.pop("model", None)
            complete_kwargs.pop("timeout", None)
            response = await self.llm_client.complete(**complete_kwargs)

        if hasattr(response, "final_response"):
            content = response.final_response.strip()
        elif hasattr(response, "content"):
            content = response.content.strip()
        else:
            content = str(response).strip()

        # Extract JSON from markdown code blocks if present
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()

        try:
            data = json.loads(content)
            if isinstance(data, dict) and "facts" in data:
                facts = data["facts"]
                if isinstance(facts, list):
                    return [str(f) for f in facts[:self.max_facts]]
            # Try parsing as FactsResponse
            response_obj = FactsResponse(**data)
            return response_obj.facts[:self.max_facts] if response_obj.facts else []
        except (json.JSONDecodeError, ValueError, TypeError) as e:
            logger.warning(f"Failed to parse LLM response as facts: {e}. Content: {content[:200]}")
            # Fallback: try to extract facts from plain text (one per line)
            lines = [line.strip() for line in content.split("\n") if line.strip()]
            # Filter out lines that look like JSON structure or metadata
            facts = [
                line for line in lines[:self.max_facts]
                if not line.startswith("{") and not line.startswith("[") and len(line) > 10
            ]
            return facts
