"""Chunking agent for adaptive chunking strategy selection.

Uses LLM to analyze document previews and select the optimal chunking strategy.
"""

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from gluellm import GlueLLM
    from spiderweb.chunkers.base import Chunker

from pydantic import BaseModel, Field

from spiderweb.config import settings
from spiderweb.models.config import ChunkerConfig
from spiderweb.observability.logging_config import get_logger
from spiderweb.registry import chunker_registry

logger = get_logger(__name__)


class ChunkerChoice(BaseModel):
    """LLM output for chunking strategy selection.
    
    Generated by analyzing document preview and selecting the best chunking strategy.
    """
    
    strategy: Literal["hierarchical", "semantic", "sentence", "sliding_window"] = Field(
        description="The chunking strategy to use for this document"
    )
    rationale: str = Field(
        description="Brief explanation of why this strategy was chosen"
    )


def _get_chunking_strategies_description() -> str:
    """Get a concise description of available chunking strategies for the LLM prompt."""
    return """Available chunking strategies:

1. **hierarchical** - Best for markdown documents, technical documentation, or any document with clear heading structure. Preserves document hierarchy and creates parent-child relationships between chunks. Fast, no LLM required.

2. **semantic** - Best for documents without clear structure, when topics shift without heading markers, or long-form text with multiple subjects. Uses embeddings to detect topic changes. Slower, requires LLM for embeddings.

3. **sentence** - Best for articles, prose, or documents where sentence integrity is important. Groups consecutive sentences until reaching size limit. Fast, no LLM required.

4. **sliding_window** - Best for any text type when you need simple, consistent chunking. Creates fixed-size chunks with configurable overlap. Fastest and simplest, no LLM required."""


async def choose_chunking_strategy(
    llm_client: "GlueLLM",
    document_preview: str,
    file_name: str,
    model: str | None = None,
) -> ChunkerChoice:
    """Choose the best chunking strategy for a document using LLM analysis.
    
    Analyzes a document preview (first N characters) and file name to determine
    the optimal chunking strategy based on document characteristics.
    
    Args:
        llm_client: GlueLLM client for LLM operations
        document_preview: Preview of document content (first 3000-4000 chars recommended)
        file_name: Name of the file being processed
        model: Optional model name override
        
    Returns:
        ChunkerChoice with selected strategy and rationale
        
    Example:
        >>> from gluellm import GlueLLM
        >>> llm = GlueLLM()
        >>> choice = await choose_chunking_strategy(
        ...     llm_client=llm,
        ...     document_preview="# Introduction\\n\\nThis is a markdown doc...",
        ...     file_name="README.md"
        ... )
        >>> print(choice.strategy)  # "hierarchical"
    """
    strategies_desc = _get_chunking_strategies_description()
    
    prompt = f"""Analyze the following document preview and select the best chunking strategy.

File name: {file_name}

Document preview:
{document_preview}

{strategies_desc}

Consider:
- File extension and name (e.g., .md suggests hierarchical, .txt might suggest sentence)
- Document structure (presence of headings, markdown formatting)
- Content type (prose, technical docs, unstructured text)
- Whether semantic boundaries matter more than structural boundaries

Return your choice as JSON with "strategy" (one of: hierarchical, semantic, sentence, sliding_window) and "rationale" (brief explanation)."""

    try:
        # Try structured_complete first (preferred)
        try:
            from gluellm.api import structured_complete
            
            choice = await structured_complete(
                user_message=prompt,
                response_format=ChunkerChoice,
                model=model,
                timeout=settings.llm_timeout,
            )
            logger.debug(f"Selected chunking strategy '{choice.strategy}' for {file_name}: {choice.rationale}")
            return choice
        except (ImportError, AttributeError, Exception) as e:
            logger.debug(f"structured_complete not available, falling back to complete(): {e}")
            # Fallback to complete() + JSON parse
            pass
    except Exception:
        # Fallback to complete() + JSON parse
        pass
    
    # Fallback: use complete() and parse JSON
    complete_kwargs: dict[str, Any] = {
        "user_message": prompt,
        "temperature": 0.3,  # Lower temperature for more consistent choices
        "timeout": settings.llm_timeout,
    }
    if model is not None:
        complete_kwargs["model"] = model
    
    try:
        response = await llm_client.complete(**complete_kwargs)
    except TypeError:
        # Handle clients that don't accept these kwargs
        complete_kwargs.pop("temperature", None)
        complete_kwargs.pop("model", None)
        complete_kwargs.pop("timeout", None)
        response = await llm_client.complete(**complete_kwargs)
    
    if hasattr(response, "final_response"):
        content = response.final_response.strip()
    elif hasattr(response, "content"):
        content = response.content.strip()
    else:
        content = str(response).strip()
    
    # Extract JSON from markdown code blocks if present
    import json
    
    if "```json" in content:
        content = content.split("```json")[1].split("```")[0].strip()
    elif "```" in content:
        content = content.split("```")[1].split("```")[0].strip()
    
    try:
        data = json.loads(content)
        choice = ChunkerChoice(**data)
        logger.debug(f"Selected chunking strategy '{choice.strategy}' for {file_name}: {choice.rationale}")
        return choice
    except (json.JSONDecodeError, ValueError, TypeError) as e:
        logger.warning(f"Failed to parse LLM response as ChunkerChoice: {e}. Content: {content[:200]}")
        # Fallback: try to extract strategy from text
        content_lower = content.lower()
        if "hierarchical" in content_lower or "hierarchy" in content_lower or ".md" in file_name.lower():
            strategy = "hierarchical"
            rationale = "Fallback: detected markdown or hierarchical structure"
        elif "semantic" in content_lower:
            strategy = "semantic"
            rationale = "Fallback: LLM suggested semantic"
        elif "sentence" in content_lower:
            strategy = "sentence"
            rationale = "Fallback: LLM suggested sentence"
        elif "sliding" in content_lower or "window" in content_lower:
            strategy = "sliding_window"
            rationale = "Fallback: LLM suggested sliding window"
        else:
            # Default fallback
            strategy = "hierarchical"
            rationale = "Fallback: defaulting to hierarchical"
        
        logger.warning(f"Using fallback strategy '{strategy}' for {file_name}")
        return ChunkerChoice(strategy=strategy, rationale=rationale)


def create_chunker_from_strategy(
    strategy: str,
    base_config: ChunkerConfig | None = None,
    llm_client: "GlueLLM | None" = None,
) -> "Chunker":
    """Create a chunker instance from a strategy name.
    
    Uses the chunker registry to instantiate the appropriate chunker class
    with the provided configuration. Handles special cases like SemanticChunker
    that require an LLM client.
    
    Args:
        strategy: Chunking strategy name (e.g., "hierarchical", "semantic")
        base_config: Base chunker configuration (strategy will be overridden)
        llm_client: LLM client (required for semantic chunking)
        
    Returns:
        Chunker instance
        
    Raises:
        KeyError: If strategy is not registered
        
    Example:
        >>> from gluellm import GlueLLM
        >>> from spiderweb.models.config import ChunkerConfig
        >>> llm = GlueLLM()
        >>> config = ChunkerConfig(max_chunk_size=2000)
        >>> chunker = create_chunker_from_strategy("semantic", config, llm)
    """
    
    # Get chunker class from registry
    if strategy not in chunker_registry:
        available = chunker_registry.list()
        raise KeyError(
            f"Unknown chunking strategy '{strategy}'. Available: {available}"
        )
    
    chunker_cls = chunker_registry.get(strategy)
    
    # Create config with the selected strategy
    if base_config:
        # Copy config and override strategy
        config_dict = base_config.model_dump()
        config_dict["strategy"] = strategy
        config = ChunkerConfig(**config_dict)
    else:
        # Create default config with strategy
        config = ChunkerConfig(strategy=strategy)
    
    # Instantiate chunker
    if hasattr(chunker_cls, "from_config"):
        # Special handling for SemanticChunker which needs llm_client
        if strategy == "semantic":
            return chunker_cls.from_config(config, llm_client=llm_client)
        else:
            return chunker_cls.from_config(config)
    else:
        # Direct instantiation (shouldn't happen for built-in chunkers, but handle it)
        return chunker_cls()
