"""Research agent module for persona-driven and goal-driven research workflows.

Provides query generation, report synthesis, and planning capabilities for
multi-crawler research workflows.
"""

from spiderweb.research.agent import (
    aggregate_traces_for_report,
    create_research_plan,
    decide_additional_queries,
    decide_additional_queries_with_reasoning,
    dedupe_listings,
    extract_listings_from_page,
    format_listings_as_list,
    gather_listings_from_traces,
    generate_more_queries,
    generate_research_queries,
    reflect_and_plan_next_round,
    spill_trace_content_to_dir,
    spill_trace_to_store,
    summarize_content_batch,
    summarize_traces_in_batches,
    synthesize_report,
    synthesize_report_from_listings,
    synthesize_report_from_listings_and_summaries,
    synthesize_report_from_summaries,
    validate_items,
)
from spiderweb.research.models import (
    AcceptanceCriteria,
    ExpansionDecision,
    GoalResult,
    ItemVerdict,
    ListingExtractionPayload,
    ListingItem,
    PageListings,
    PipelineType,
    ResearchPlan,
    ResearchReportResult,
    RoundReflection,
    SearchStrategy,
)
from spiderweb.research.storage import MarkdownResearchStore, ResearchContentStore

__all__ = [
    "aggregate_traces_for_report",
    "create_research_plan",
    "decide_additional_queries",
    "decide_additional_queries_with_reasoning",
    "dedupe_listings",
    "extract_listings_from_page",
    "format_listings_as_list",
    "gather_listings_from_traces",
    "generate_more_queries",
    "generate_research_queries",
    "reflect_and_plan_next_round",
    "spill_trace_content_to_dir",
    "spill_trace_to_store",
    "summarize_content_batch",
    "summarize_traces_in_batches",
    "synthesize_report",
    "synthesize_report_from_listings",
    "synthesize_report_from_listings_and_summaries",
    "synthesize_report_from_summaries",
    "validate_items",
    "AcceptanceCriteria",
    "ExpansionDecision",
    "GoalResult",
    "ItemVerdict",
    "ListingExtractionPayload",
    "ListingItem",
    "MarkdownResearchStore",
    "PageListings",
    "PipelineType",
    "ResearchContentStore",
    "ResearchPlan",
    "ResearchReportResult",
    "RoundReflection",
    "SearchStrategy",
]
