"""Data models for research agent workflows.

Defines structured types for research plans and results.
"""

from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field

from spiderweb.search.trace import SearchCrawlTrace


class ResearchPlan(BaseModel):
    """Structured plan for research execution.
    
    Generated by LLM from a goal (and optional persona/instructions).
    Defines what queries to run and how to frame the final report.
    """
    
    queries: list[str] = Field(
        description="List of search/crawl queries to execute for comprehensive coverage",
        min_length=1,
    )
    report_focus: str = Field(
        description="Description of what the final report should address or emphasize",
    )
    rationale: str | None = Field(
        default=None,
        description="Optional explanation of why these queries were chosen",
    )


class ExpansionDecision(BaseModel):
    """LLM output for whether to run more queries and which ones.
    
    Used when evaluating if additional web searches are needed after
    initial crawls, based on the content gathered so far.
    """
    
    reasoning: str = Field(
        description="Brief analysis of the crawled content: what we learned, what is still missing or under-covered relative to the research task."
    )
    need_more_queries: bool = Field(
        description="True if additional web searches would significantly improve the research."
    )
    queries: list[str] = Field(
        default_factory=list,
        description="New search queries to run (empty if need_more_queries is False).",
    )


@dataclass
class ResearchReportResult:
    """Result from research_and_report execution.
    
    Contains the synthesized report, traces from parallel crawls,
    and metadata about the research session.
    """
    
    report: str | Any  # str for markdown, or BaseModel instance for structured
    traces: list[SearchCrawlTrace] = field(default_factory=list)
    queries_used: list[str] = field(default_factory=list)
    aggregated_context_preview: str | None = None


@dataclass
class GoalResult:
    """Result from achieve_goal execution.
    
    Contains both the plan that was generated and the execution results.
    Provides transparency into what the agent decided to do.
    """
    
    plan: ResearchPlan
    report: str | Any  # str for markdown, or BaseModel instance for structured
    traces: list[SearchCrawlTrace] = field(default_factory=list)
    queries_used: list[str] = field(default_factory=list)
